In [2]:
import numpy as np
import pandas as pd

### Q1. Pandas version

In [3]:
pd.__version__

'3.0.6'

In [4]:
df = pd.read_csv("C:/zoom-ml/01-intro/dataset/car.csv")

### Q2. Record counts

In [5]:
df.shape[0]

10000

In [6]:
df.head(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


### Q3. Fuel types

In [9]:
df['fuel_type'].nunique()

3

### Q4. Missing values

In [7]:
df.isnull().any().sum()

np.int64(2)

### Q5. Max fuel efficiency

In [17]:
df.groupby('origin').fuel_efficiency_mpg.max()

origin
Asia      41.2
Europe    39.4
USA       38.2
Name: fuel_efficiency_mpg, dtype: float64

### Q6. Median

In [19]:
med_hp = df.horsepower.median()
med_hp

np.float64(254.0)

In [20]:
mod_hp = df.horsepower.mode()
mod_hp

0    252.0
Name: horsepower, dtype: float64

In [25]:
df['horsepower'].isnull().any()

np.True_

In [29]:
df['horsepower'] = df['horsepower'].fillna(mod_hp[0])
df['horsepower'].isnull().any()

np.False_

In [30]:
df['horsepower'].median()

np.float64(252.0)

### Q7. Sum of weights

In [8]:
X = df[df['origin'] == 'Asia'].reset_index().loc[:6,['vehicle_weight','model_year']].to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [9]:
XT = X.T
XT

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [10]:
XTX = XT.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [11]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [12]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [13]:
w = XTX_inv.dot(XT).dot(y)
w

array([0.13644777, 0.2327492 ])

In [15]:
w.sum().round(4)

np.float64(0.3692)